---
- hosts: all
  become: true
  tasks:

  - name: update repository index for Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package and php packages for Ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for CentOS
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache package and php packages for CentOS
    yum:
      name:
        - httpd
        - php
    when: ansible_distribution == "CentOS"
